name: Release

on:
  push:
    tags:
      - '*.*.*'
jobs:
  build:
    strategy:
      fail-fast: false
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build and Test
        run: ./Build.ps1
        shell: pwsh
      - name: Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: artifacts/**/*